'use client'
import { FormEvent, useEffect, useState } from 'react'

type Customer={email:string;active:boolean;source:string|null;blocked_reason:string|null;updated_at:string}
type Log={email:string|null;event_type:string;created_at:string;metadata:Record<string,unknown>}

export default function AdminPanel(){
 const [logged,setLogged]=useState(false),[error,setError]=useState(''),[customers,setCustomers]=useState<Customer[]>([]),[logs,setLogs]=useState<Log[]>([]),[q,setQ]=useState('')
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const r=await fetch('/api/auth/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:f.get('username'),secret:f.get('secret')})});if(!r.ok){setError('Credenciais inválidas');return}setLogged(true);load()}
 async function load(){const [a,b]=await Promise.all([fetch('/api/admin/customers'),fetch('/api/admin/logs')]);if(a.status===401){setLogged(false);return}const ca=await a.json(),lb=await b.json();setCustomers(ca.customers||[]);setLogs(lb.logs||[]);setLogged(true)}
 useEffect(()=>{load()},[])
 async function toggle(c:Customer){await fetch('/api/admin/block',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:c.email,active:!c.active,reason:'manual_panel'})});load()}
 async function search(){const r=await fetch('/api/admin/customers?q='+encodeURIComponent(q));const d=await r.json();setCustomers(d.customers||[])}
 if(!logged)return <main className="adminLogin"><form onSubmit={login}><div className="adminBrand">P90 <b>ADMIN</b></div><h1>Painel administrativo</h1><p>Acesso restrito.</p><input name="username" placeholder="Usuário" autoComplete="username"/><input name="secret" type="password" placeholder="Senha" autoComplete="current-password"/><button>Entrar</button>{error&&<small className="error">{error}</small>}</form></main>
 return <main className="adminPage"><header><div><b>P90 ADMIN</b><small>Controle de acesso e segurança</small></div><button onClick={load}>Atualizar</button></header><section className="adminStats"><div><small>Clientes exibidos</small><b>{customers.length}</b></div><div><small>Acessos ativos</small><b>{customers.filter(x=>x.active).length}</b></div><div><small>Bloqueados</small><b>{customers.filter(x=>!x.active).length}</b></div></section><section className="adminCard"><div className="adminTitle"><div><h2>Clientes</h2><p>Bloqueie ou reative o acesso imediatamente.</p></div><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar e-mail"/><button onClick={search}>Buscar</button></div></div><div className="tableWrap"><table><thead><tr><th>E-mail</th><th>Status</th><th>Origem</th><th>Atualizado</th><th>Ação</th></tr></thead><tbody>{customers.map(c=><tr key={c.email}><td>{c.email}</td><td><span className={c.active?'statusOn':'statusOff'}>{c.active?'ATIVO':'BLOQUEADO'}</span></td><td>{c.source||'—'}</td><td>{new Date(c.updated_at).toLocaleString('pt-BR')}</td><td><button className={c.active?'danger':'success'} onClick={()=>toggle(c)}>{c.active?'Bloquear':'Reativar'}</button></td></tr>)}</tbody></table></div></section><section className="adminCard"><div className="adminTitle"><div><h2>Eventos de segurança</h2><p>Últimos 100 eventos registrados.</p></div></div><div className="logList">{logs.map((l,i)=><div key={i}><span>{l.event_type}</span><b>{l.email||'Sistema'}</b><small>{new Date(l.created_at).toLocaleString('pt-BR')}</small></div>)}</div></section></main>
}
